// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyBSsf_zxlfCz2GBPkcpQGjU7Z34ZCVy8',
    appId: '1:592393631321:web:798a339b38eb79a2f2e348',
    messagingSenderId: '592393631321',
    projectId: 'noble-cards',
    authDomain: 'noble-cards.firebaseapp.com',
    storageBucket: 'noble-cards.firebasestorage.app',
    measurementId: 'G-CXCGW38Z4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWzxqzwU-aYzcGca3i0ISWNLJZy-xDHI4',
    appId: '1:592393631321:android:1e3f70e9b8662d49f2e348',
    messagingSenderId: '592393631321',
    projectId: 'noble-cards',
    storageBucket: 'noble-cards.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzbu0x_rgKNgIGC1zdL-EgqHnbVkW_Z6w',
    appId: '1:592393631321:ios:d9eeceae7799d212f2e348',
    messagingSenderId: '592393631321',
    projectId: 'noble-cards',
    storageBucket: 'noble-cards.firebasestorage.app',
    iosBundleId: 'com.example.nobleCards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzbu0x_rgKNgIGC1zdL-EgqHnbVkW_Z6w',
    appId: '1:592393631321:ios:d9eeceae7799d212f2e348',
    messagingSenderId: '592393631321',
    projectId: 'noble-cards',
    storageBucket: 'noble-cards.firebasestorage.app',
    iosBundleId: 'com.example.nobleCards',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyBSsf_zxlfCz2GBPkcpQGjU7Z34ZCVy8',
    appId: '1:592393631321:web:4bbde0bfd793faecf2e348',
    messagingSenderId: '592393631321',
    projectId: 'noble-cards',
    authDomain: 'noble-cards.firebaseapp.com',
    storageBucket: 'noble-cards.firebasestorage.app',
    measurementId: 'G-8YWF8TQLYG',
  );
}
