import '../models/gift_card_model.dart';

class CardsService {
  Future<List<GiftCardModel>> fetchCards() async {
    await Future.delayed(const Duration(seconds: 1));
    return const [
      GiftCardModel(
        id: '1',
        name: 'Amazon',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Shopping',
        description: 'Shop millions of items online.',
        buyRate: 93.20,
        sellRate: 91.00,
        isTrending: true,
        popularityRank: 2,
      ),
      GiftCardModel(
        id: '2',
        name: 'Apple',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/0/747.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Tech',
        description: 'App Store, Apple Music, hardware.',
        buyRate: 94.50,
        sellRate: 92.30,
        isTrending: true,
        popularityRank: 1,
      ),
      GiftCardModel(
        id: '3',
        name: 'Steam',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United Kingdom',
        countryFlag: '🇬🇧',
        category: 'Gaming',
        description: 'PC games and downloadable content.',
        buyRate: 88.40,
        sellRate: 86.20,
        isTrending: true,
        popularityRank: 3,
      ),
      GiftCardModel(
        id: '4',
        name: 'Netflix',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732228.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Streaming',
        description: 'Movies, TV shows, and originals.',
        buyRate: 89.10,
        sellRate: 87.30,
        isTrending: false,
        popularityRank: 6,
      ),
      GiftCardModel(
        id: '5',
        name: 'PlayStation',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/588/588302.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Gaming',
        description: 'PS Store downloads and memberships.',
        buyRate: 91.00,
        sellRate: 89.50,
        isTrending: true,
        popularityRank: 4,
      ),
      GiftCardModel(
        id: '6',
        name: 'Spotify',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/2111/2111624.png',
        country: 'Germany',
        countryFlag: '🇩🇪',
        category: 'Music',
        description: 'Ad-free music streaming.',
        buyRate: 86.50,
        sellRate: 84.00,
        isTrending: false,
        popularityRank: 7,
      ),
      GiftCardModel(
        id: '7',
        name: 'Razer Gold',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/888/888849.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Gaming',
        description: 'Virtual credits for global games.',
        buyRate: 87.20,
        sellRate: 85.10,
        isTrending: true,
        popularityRank: 5,
      ),
      GiftCardModel(
        id: '8',
        name: 'Nike',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Fashion',
        description: 'Sportswear and apparel.',
        buyRate: 86.00,
        sellRate: 84.70,
        isTrending: false,
        popularityRank: 8,
      ),
    ];
  }
}