import '../models/gift_card_model.dart';

class CardsService {
  Future<List<GiftCardModel>> fetchCards() async {
    await Future.delayed(const Duration(seconds: 1));
    return const [
      GiftCardModel(
        id: '1',
        name: 'Amazon',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Shopping',
        description: 'Shop millions of items online.',
        buyRate: 93.20,
        sellRate: 91.00,
        isTrending: true,
        popularityRank: 2,
      ),
      GiftCardModel(
        id: '2',
        name: 'Apple',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/0/747.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Tech',
        description: 'App Store, Apple Music, hardware.',
        buyRate: 94.50,
        sellRate: 92.30,
        isTrending: true,
        popularityRank: 1,
      ),
      GiftCardModel(
        id: '3',
        name: 'Steam',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United Kingdom',
        countryFlag: '🇬🇧',
        category: 'Gaming',
        description: 'PC games and downloadable content.',
        buyRate: 88.40,
        sellRate: 86.20,
        isTrending: true,
        popularityRank: 3,
      ),
      GiftCardModel(
        id: '4',
        name: 'Netflix',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732228.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Streaming',
        description: 'Movies, TV shows, and originals.',
        buyRate: 89.10,
        sellRate: 87.30,
        isTrending: false,
        popularityRank: 6,
      ),
      GiftCardModel(
        id: '5',
        name: 'PlayStation Store',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/588/588302.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Gaming',
        description: 'PS Store downloads and memberships.',
        buyRate: 91.00,
        sellRate: 89.50,
        isTrending: true,
        popularityRank: 4,
      ),
      GiftCardModel(
        id: '6',
        name: 'Spotify',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/2111/2111624.png',
        country: 'Germany',
        countryFlag: '🇩🇪',
        category: 'Music',
        description: 'Ad-free music streaming.',
        buyRate: 86.50,
        sellRate: 84.00,
        isTrending: false,
        popularityRank: 7,
      ),
      GiftCardModel(
        id: '7',
        name: 'Razer Gold',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/888/888849.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Gaming',
        description: 'Virtual credits for global games.',
        buyRate: 87.20,
        sellRate: 85.10,
        isTrending: true,
        popularityRank: 5,
      ),
      GiftCardModel(
        id: '8',
        name: 'Nike',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Fashion',
        description: 'Sportswear and apparel.',
        buyRate: 86.00,
        sellRate: 84.70,
        isTrending: false,
        popularityRank: 8,
      ),
      GiftCardModel(
        id: '9',
        name: 'Walmart',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Shopping',
        description: 'Everyday essentials and household deals.',
        buyRate: 92.60,
        sellRate: 90.40,
        popularityRank: 9,
      ),
      GiftCardModel(
        id: '10',
        name: 'Target',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Shopping',
        description: 'Fast retail gift card for everyday shopping.',
        buyRate: 91.80,
        sellRate: 89.90,
        popularityRank: 10,
      ),
      GiftCardModel(
        id: '11',
        name: 'Best Buy',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/588/588302.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Shopping',
        description: 'Tech and electronics marketplace.',
        buyRate: 90.70,
        sellRate: 88.80,
        popularityRank: 11,
      ),
      GiftCardModel(
        id: '12',
        name: 'eBay',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732228.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Shopping',
        description: 'Marketplace for collectibles and deals.',
        buyRate: 89.90,
        sellRate: 87.70,
        popularityRank: 12,
      ),
      GiftCardModel(
        id: '13',
        name: 'Etsy',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/2111/2111624.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Shopping',
        description: 'Handmade and unique goods.',
        buyRate: 88.60,
        sellRate: 86.50,
        popularityRank: 13,
      ),
      GiftCardModel(
        id: '14',
        name: 'AliExpress',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/888/888849.png',
        country: 'China',
        countryFlag: '🇨🇳',
        category: 'Shopping',
        description: 'Global online retail marketplace.',
        buyRate: 85.70,
        sellRate: 83.10,
        popularityRank: 14,
      ),
      GiftCardModel(
        id: '15',
        name: 'Temu',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'Singapore',
        countryFlag: '🇸🇬',
        category: 'Shopping',
        description: 'Value-first shopping and lifestyle deals.',
        buyRate: 84.80,
        sellRate: 82.20,
        popularityRank: 15,
      ),
      GiftCardModel(
        id: '16',
        name: 'SHEIN',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'China',
        countryFlag: '🇨🇳',
        category: 'Shopping',
        description: 'Fashion and lifestyle deals.',
        buyRate: 83.90,
        sellRate: 81.40,
        popularityRank: 16,
      ),
      GiftCardModel(
        id: '17',
        name: "Macy's",
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732228.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Shopping',
        description: 'Department store shopping card.',
        buyRate: 88.10,
        sellRate: 85.90,
        popularityRank: 17,
      ),
      GiftCardModel(
        id: '18',
        name: 'Costco',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Shopping',
        description: 'Bulk shopping and warehouse savings.',
        buyRate: 90.40,
        sellRate: 88.20,
        popularityRank: 18,
      ),
      GiftCardModel(
        id: '19',
        name: 'Home Depot',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Shopping',
        description: 'Hardware, tools, and home improvement.',
        buyRate: 88.30,
        sellRate: 86.10,
        popularityRank: 19,
      ),
      GiftCardModel(
        id: '20',
        name: "Lowe's",
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Shopping',
        description: 'Home improvement essentials.',
        buyRate: 87.40,
        sellRate: 85.30,
        popularityRank: 20,
      ),
      GiftCardModel(
        id: '21',
        name: 'IKEA',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732228.png',
        country: 'Sweden',
        countryFlag: '🇸🇪',
        category: 'Shopping',
        description: 'Furniture and home lifestyle goods.',
        buyRate: 85.20,
        sellRate: 82.90,
        popularityRank: 21,
      ),
      GiftCardModel(
        id: '22',
        name: 'Wayfair',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Shopping',
        description: 'Home décor and furniture.',
        buyRate: 87.80,
        sellRate: 85.80,
        popularityRank: 22,
      ),
      GiftCardModel(
        id: '23',
        name: 'Argos',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United Kingdom',
        countryFlag: '🇬🇧',
        category: 'Shopping',
        description: 'Popular UK retail marketplace.',
        buyRate: 86.60,
        sellRate: 84.40,
        popularityRank: 23,
      ),
      GiftCardModel(
        id: '24',
        name: 'Noon',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'UAE',
        countryFlag: '🇦🇪',
        category: 'Shopping',
        description: 'Middle East shopping destination.',
        buyRate: 84.90,
        sellRate: 82.70,
        popularityRank: 24,
      ),
      GiftCardModel(
        id: '25',
        name: 'Carrefour',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'France',
        countryFlag: '🇫🇷',
        category: 'Shopping',
        description: 'Retail and supermarket shopping.',
        buyRate: 85.60,
        sellRate: 83.50,
        popularityRank: 25,
      ),
      GiftCardModel(
        id: '26',
        name: 'Jumia',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'Nigeria',
        countryFlag: '🇳🇬',
        category: 'Shopping',
        description: 'African e-commerce retail leader.',
        buyRate: 83.50,
        sellRate: 81.10,
        popularityRank: 26,
      ),
      GiftCardModel(
        id: '27',
        name: 'Konga',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'Nigeria',
        countryFlag: '🇳🇬',
        category: 'Shopping',
        description: 'Online retail for everyday essentials.',
        buyRate: 82.70,
        sellRate: 80.40,
        popularityRank: 27,
      ),
      GiftCardModel(
        id: '28',
        name: 'Xbox',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Gaming',
        description: 'Console and game credits.',
        buyRate: 90.10,
        sellRate: 88.10,
        isTrending: true,
        popularityRank: 28,
      ),
      GiftCardModel(
        id: '29',
        name: 'Nintendo eShop',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/588/588302.png',
        country: 'Japan',
        countryFlag: '🇯🇵',
        category: 'Gaming',
        description: 'Nintendo digital game store.',
        buyRate: 87.10,
        sellRate: 85.00,
        popularityRank: 29,
      ),
      GiftCardModel(
        id: '30',
        name: 'Epic Games',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/588/588302.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Gaming',
        description: 'Epic rewards and game offers.',
        buyRate: 89.20,
        sellRate: 87.10,
        popularityRank: 30,
      ),
      GiftCardModel(
        id: '31',
        name: 'EA Play',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Gaming',
        description: 'EA subscription and digital benefits.',
        buyRate: 88.40,
        sellRate: 86.30,
        popularityRank: 31,
      ),
      GiftCardModel(
        id: '32',
        name: 'Roblox',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/888/888849.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Gaming',
        description: 'In-game currency and creators economy.',
        buyRate: 87.60,
        sellRate: 85.40,
        popularityRank: 32,
      ),
      GiftCardModel(
        id: '33',
        name: 'Riot Games',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Gaming',
        description: 'League and title bundles.',
        buyRate: 88.80,
        sellRate: 86.70,
        popularityRank: 33,
      ),
      GiftCardModel(
        id: '34',
        name: 'Blizzard',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Gaming',
        description: 'World of Warcraft and Blizzard store.',
        buyRate: 86.90,
        sellRate: 84.90,
        popularityRank: 34,
      ),
      GiftCardModel(
        id: '35',
        name: 'PUBG Mobile',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'Singapore',
        countryFlag: '🇸🇬',
        category: 'Gaming',
        description: 'Mobile battle royale top-ups.',
        buyRate: 85.40,
        sellRate: 83.20,
        popularityRank: 35,
      ),
      GiftCardModel(
        id: '36',
        name: 'Fortnite V-Bucks',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Gaming',
        description: 'Battle pass and cosmetic currency.',
        buyRate: 90.80,
        sellRate: 88.70,
        popularityRank: 36,
      ),
      GiftCardModel(
        id: '37',
        name: 'Free Fire',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'Singapore',
        countryFlag: '🇸🇬',
        category: 'Gaming',
        description: 'Garena top-up credit store.',
        buyRate: 84.70,
        sellRate: 82.50,
        popularityRank: 37,
      ),
      GiftCardModel(
        id: '38',
        name: 'Valorant',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Gaming',
        description: 'Riot in-game points and bundles.',
        buyRate: 89.50,
        sellRate: 87.40,
        popularityRank: 38,
      ),
      GiftCardModel(
        id: '39',
        name: 'Minecraft',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'Germany',
        countryFlag: '🇩🇪',
        category: 'Gaming',
        description: 'Minecoins and premium play content.',
        buyRate: 88.40,
        sellRate: 86.10,
        popularityRank: 39,
      ),
      GiftCardModel(
        id: '40',
        name: 'League of Legends',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Gaming',
        description: 'Riot points and digital bundles.',
        buyRate: 89.80,
        sellRate: 87.50,
        popularityRank: 40,
      ),
      GiftCardModel(
        id: '41',
        name: 'Genshin Impact',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'Japan',
        countryFlag: '🇯🇵',
        category: 'Gaming',
        description: 'Premium in-game currency.',
        buyRate: 86.20,
        sellRate: 84.10,
        popularityRank: 41,
      ),
      GiftCardModel(
        id: '42',
        name: 'Apex Legends',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Gaming',
        description: 'Digital store credits for EA titles.',
        buyRate: 88.20,
        sellRate: 86.00,
        popularityRank: 42,
      ),
      GiftCardModel(
        id: '43',
        name: 'Disney+',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732228.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Streaming',
        description: 'Family entertainment and originals.',
        buyRate: 88.90,
        sellRate: 86.80,
        popularityRank: 43,
      ),
      GiftCardModel(
        id: '44',
        name: 'Prime Video',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Streaming',
        description: 'Streaming catalog and premium series.',
        buyRate: 87.40,
        sellRate: 85.30,
        popularityRank: 44,
      ),
      GiftCardModel(
        id: '45',
        name: 'Apple TV+',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/0/747.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Streaming',
        description: 'Apple Originals and premium watchlist.',
        buyRate: 90.60,
        sellRate: 88.40,
        popularityRank: 45,
      ),
      GiftCardModel(
        id: '46',
        name: 'Hulu',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732228.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Streaming',
        description: 'Live TV and entertainment streaming.',
        buyRate: 89.30,
        sellRate: 87.10,
        popularityRank: 46,
      ),
      GiftCardModel(
        id: '47',
        name: 'HBO Max',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732228.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Streaming',
        description: 'Premium series and blockbuster movies.',
        buyRate: 90.10,
        sellRate: 87.90,
        popularityRank: 47,
      ),
      GiftCardModel(
        id: '48',
        name: 'Paramount+',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732228.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Streaming',
        description: 'Live sports and all-new originals.',
        buyRate: 86.70,
        sellRate: 84.60,
        popularityRank: 48,
      ),
      GiftCardModel(
        id: '49',
        name: 'Crunchyroll',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732228.png',
        country: 'Japan',
        countryFlag: '🇯🇵',
        category: 'Streaming',
        description: 'Anime subscription and premium access.',
        buyRate: 85.90,
        sellRate: 83.70,
        popularityRank: 49,
      ),
      GiftCardModel(
        id: '50',
        name: 'Peacock',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732228.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Streaming',
        description: 'NBC and entertainment streaming.',
        buyRate: 84.40,
        sellRate: 82.30,
        popularityRank: 50,
      ),
      GiftCardModel(
        id: '51',
        name: 'YouTube Premium',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732228.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Streaming',
        description: 'Ad-free video and background play.',
        buyRate: 91.40,
        sellRate: 89.30,
        popularityRank: 51,
      ),
      GiftCardModel(
        id: '52',
        name: 'DAZN',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732228.png',
        country: 'United Kingdom',
        countryFlag: '🇬🇧',
        category: 'Streaming',
        description: 'Sports streaming subscription.',
        buyRate: 85.30,
        sellRate: 83.10,
        popularityRank: 52,
      ),
      GiftCardModel(
        id: '53',
        name: 'Discovery+',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732228.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Streaming',
        description: 'Documentary and lifestyle streaming.',
        buyRate: 84.80,
        sellRate: 82.60,
        popularityRank: 53,
      ),
      GiftCardModel(
        id: '54',
        name: 'Showmax',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732228.png',
        country: 'South Africa',
        countryFlag: '🇿🇦',
        category: 'Streaming',
        description: 'African entertainment platform.',
        buyRate: 83.80,
        sellRate: 81.70,
        popularityRank: 54,
      ),
      GiftCardModel(
        id: '55',
        name: 'Uber Eats',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Food',
        description: 'Food delivery and everyday meals.',
        buyRate: 87.20,
        sellRate: 85.10,
        popularityRank: 55,
      ),
      GiftCardModel(
        id: '56',
        name: 'DoorDash',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Food',
        description: 'Restaurant-to-door delivery credits.',
        buyRate: 86.50,
        sellRate: 84.40,
        popularityRank: 56,
      ),
      GiftCardModel(
        id: '57',
        name: 'Grubhub',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Food',
        description: 'Fast food and restaurant delivery.',
        buyRate: 85.80,
        sellRate: 83.70,
        popularityRank: 57,
      ),
      GiftCardModel(
        id: '58',
        name: 'Deliveroo',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United Kingdom',
        countryFlag: '🇬🇧',
        category: 'Food',
        description: 'Popular UK restaurant delivery platform.',
        buyRate: 84.30,
        sellRate: 82.20,
        popularityRank: 58,
      ),
      GiftCardModel(
        id: '59',
        name: 'Just Eat',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United Kingdom',
        countryFlag: '🇬🇧',
        category: 'Food',
        description: 'Food delivery for takeaway favorites.',
        buyRate: 84.10,
        sellRate: 82.00,
        popularityRank: 59,
      ),
      GiftCardModel(
        id: '60',
        name: 'Starbucks',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Food',
        description: 'Coffeehouse drinks and bakery items.',
        buyRate: 89.10,
        sellRate: 87.00,
        popularityRank: 60,
      ),
      GiftCardModel(
        id: '61',
        name: "McDonald's",
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'Canada',
        countryFlag: '🇨🇦',
        category: 'Food',
        description: 'Quick-service meals and beverages.',
        buyRate: 86.20,
        sellRate: 84.10,
        popularityRank: 61,
      ),
      GiftCardModel(
        id: '62',
        name: 'KFC',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Food',
        description: 'Fried chicken and combo meals.',
        buyRate: 85.20,
        sellRate: 83.10,
        popularityRank: 62,
      ),
      GiftCardModel(
        id: '63',
        name: 'Burger King',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Food',
        description: 'Fast-food favorites and value meals.',
        buyRate: 84.60,
        sellRate: 82.50,
        popularityRank: 63,
      ),
      GiftCardModel(
        id: '64',
        name: 'Pizza Hut',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Food',
        description: 'Pizza and family meal orders.',
        buyRate: 84.00,
        sellRate: 81.90,
        popularityRank: 64,
      ),
      GiftCardModel(
        id: '65',
        name: "Domino's",
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Food',
        description: 'Pizza delivery and pickup.',
        buyRate: 83.90,
        sellRate: 81.80,
        popularityRank: 65,
      ),
      GiftCardModel(
        id: '66',
        name: 'Subway',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Food',
        description: 'Sandwich and fresh meal credit.',
        buyRate: 83.20,
        sellRate: 81.10,
        popularityRank: 66,
      ),
      GiftCardModel(
        id: '67',
        name: 'Chipotle',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Food',
        description: 'Fresh bowl and burrito rewards.',
        buyRate: 85.40,
        sellRate: 83.30,
        popularityRank: 67,
      ),
      GiftCardModel(
        id: '68',
        name: 'Taco Bell',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Food',
        description: 'Mexican-inspired quick meals.',
        buyRate: 84.50,
        sellRate: 82.40,
        popularityRank: 68,
      ),
      GiftCardModel(
        id: '69',
        name: "Dunkin'",
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Food',
        description: 'Coffee, donuts, and breakfast.',
        buyRate: 83.70,
        sellRate: 81.60,
        popularityRank: 69,
      ),
      GiftCardModel(
        id: '70',
        name: 'Tim Hortons',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'Canada',
        countryFlag: '🇨🇦',
        category: 'Food',
        description: 'Coffee, pastries, and quick bites.',
        buyRate: 82.90,
        sellRate: 80.80,
        popularityRank: 70,
      ),
      GiftCardModel(
        id: '71',
        name: 'Airbnb',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Travel',
        description: 'Travel stays and getaway reservations.',
        buyRate: 91.30,
        sellRate: 89.10,
        popularityRank: 71,
      ),
      GiftCardModel(
        id: '72',
        name: 'Booking.com',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'Netherlands',
        countryFlag: '🇳🇱',
        category: 'Travel',
        description: 'Hotel bookings and travel stays.',
        buyRate: 90.80,
        sellRate: 88.60,
        popularityRank: 72,
      ),
      GiftCardModel(
        id: '73',
        name: 'Expedia',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Travel',
        description: 'Travel packages and reservations.',
        buyRate: 89.60,
        sellRate: 87.40,
        popularityRank: 73,
      ),
      GiftCardModel(
        id: '74',
        name: 'Hotels.com',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Travel',
        description: 'Hotel bookings and travel perks.',
        buyRate: 88.60,
        sellRate: 86.40,
        popularityRank: 74,
      ),
      GiftCardModel(
        id: '75',
        name: 'Uber',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Travel',
        description: 'Ride hailing and local transit.',
        buyRate: 87.90,
        sellRate: 85.70,
        popularityRank: 75,
      ),
      GiftCardModel(
        id: '76',
        name: 'Lyft',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Travel',
        description: 'Local rides and ride-share travel.',
        buyRate: 86.40,
        sellRate: 84.30,
        popularityRank: 76,
      ),
      GiftCardModel(
        id: '77',
        name: 'Marriott',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Travel',
        description: 'Hotel stays and premium travel perks.',
        buyRate: 89.10,
        sellRate: 86.90,
        popularityRank: 77,
      ),
      GiftCardModel(
        id: '78',
        name: 'Hilton',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Travel',
        description: 'Hotel reservations and rewards.',
        buyRate: 88.40,
        sellRate: 86.20,
        popularityRank: 78,
      ),
      GiftCardModel(
        id: '79',
        name: 'IHG',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United Kingdom',
        countryFlag: '🇬🇧',
        category: 'Travel',
        description: 'International hotel bookable credit.',
        buyRate: 87.60,
        sellRate: 85.40,
        popularityRank: 79,
      ),
      GiftCardModel(
        id: '80',
        name: 'Agoda',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'Singapore',
        countryFlag: '🇸🇬',
        category: 'Travel',
        description: 'Travel bookings and hotel offers.',
        buyRate: 86.80,
        sellRate: 84.60,
        popularityRank: 80,
      ),
      GiftCardModel(
        id: '81',
        name: 'Delta Airlines',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Travel',
        description: 'Flights and airline travel credits.',
        buyRate: 90.90,
        sellRate: 88.70,
        popularityRank: 81,
      ),
      GiftCardModel(
        id: '82',
        name: 'Emirates',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'UAE',
        countryFlag: '🇦🇪',
        category: 'Travel',
        description: 'Airline travel and premium cabin booking.',
        buyRate: 89.40,
        sellRate: 87.20,
        popularityRank: 82,
      ),
      GiftCardModel(
        id: '83',
        name: 'British Airways',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United Kingdom',
        countryFlag: '🇬🇧',
        category: 'Travel',
        description: 'Flights and long-haul travel credit.',
        buyRate: 88.60,
        sellRate: 86.40,
        popularityRank: 83,
      ),
      GiftCardModel(
        id: '84',
        name: 'American Airlines',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Travel',
        description: 'Airline bookings and travel vouchers.',
        buyRate: 87.40,
        sellRate: 85.30,
        popularityRank: 84,
      ),
      GiftCardModel(
        id: '85',
        name: 'Southwest Airlines',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Travel',
        description: 'Domestic and long-distance travel credit.',
        buyRate: 86.70,
        sellRate: 84.50,
        popularityRank: 85,
      ),
      GiftCardModel(
        id: '86',
        name: 'Visa Gift Card',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Finance',
        description: 'Flexible prepaid spending for retail.',
        buyRate: 91.80,
        sellRate: 89.60,
        popularityRank: 86,
      ),
      GiftCardModel(
        id: '87',
        name: 'Mastercard Gift Card',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Finance',
        description: 'Global spending flexibility.',
        buyRate: 91.10,
        sellRate: 88.90,
        popularityRank: 87,
      ),
      GiftCardModel(
        id: '88',
        name: 'American Express Gift Card',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Finance',
        description: 'Premium prepaid spending credit.',
        buyRate: 90.30,
        sellRate: 88.20,
        popularityRank: 88,
      ),
      GiftCardModel(
        id: '89',
        name: 'Vanilla Visa',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'Canada',
        countryFlag: '🇨🇦',
        category: 'Finance',
        description: 'Prepaid Visa for easy online spend.',
        buyRate: 89.70,
        sellRate: 87.50,
        popularityRank: 89,
      ),
      GiftCardModel(
        id: '90',
        name: 'One4All',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United Kingdom',
        countryFlag: '🇬🇧',
        category: 'Finance',
        description: 'High-street shopping voucher.',
        buyRate: 88.50,
        sellRate: 86.30,
        popularityRank: 90,
      ),
      GiftCardModel(
        id: '91',
        name: 'Flexepin',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'Canada',
        countryFlag: '🇨🇦',
        category: 'Finance',
        description: 'Voucher-based payment method.',
        buyRate: 85.90,
        sellRate: 83.70,
        popularityRank: 91,
      ),
      GiftCardModel(
        id: '92',
        name: 'Paysafecard',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'Germany',
        countryFlag: '🇩🇪',
        category: 'Finance',
        description: 'Online prepaid cash card.',
        buyRate: 86.30,
        sellRate: 84.10,
        popularityRank: 92,
      ),
      GiftCardModel(
        id: '93',
        name: 'SecureSpend',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Finance',
        description: 'Secure online gift card payment option.',
        buyRate: 84.80,
        sellRate: 82.60,
        popularityRank: 93,
      ),
      GiftCardModel(
        id: '94',
        name: 'MyPrepaidCenter',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Finance',
        description: 'Prepaid reloadable value card.',
        buyRate: 83.60,
        sellRate: 81.40,
        popularityRank: 94,
      ),
      GiftCardModel(
        id: '95',
        name: 'Apple Music',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/0/747.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Music',
        description: 'Streaming music and curated playlists.',
        buyRate: 89.70,
        sellRate: 87.50,
        popularityRank: 95,
      ),
      GiftCardModel(
        id: '96',
        name: 'YouTube Music',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732228.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Music',
        description: 'Music streaming within YouTube ecosystem.',
        buyRate: 87.20,
        sellRate: 85.10,
        popularityRank: 96,
      ),
      GiftCardModel(
        id: '97',
        name: 'Amazon Music',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Music',
        description: 'On-demand music and playlists.',
        buyRate: 86.40,
        sellRate: 84.30,
        popularityRank: 97,
      ),
      GiftCardModel(
        id: '98',
        name: 'Deezer',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/2111/2111624.png',
        country: 'France',
        countryFlag: '🇫🇷',
        category: 'Music',
        description: 'Premium music streaming',
        buyRate: 84.60,
        sellRate: 82.50,
        popularityRank: 98,
      ),
      GiftCardModel(
        id: '99',
        name: 'Tidal',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/2111/2111624.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Music',
        description: 'High-fidelity music playback.',
        buyRate: 85.40,
        sellRate: 83.30,
        popularityRank: 99,
      ),
      GiftCardModel(
        id: '100',
        name: 'Pandora',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/2111/2111624.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Music',
        description: 'Radio and curated music recommendations.',
        buyRate: 84.10,
        sellRate: 82.00,
        popularityRank: 100,
      ),
      GiftCardModel(
        id: '101',
        name: 'SoundCloud Go',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/2111/2111624.png',
        country: 'Germany',
        countryFlag: '🇩🇪',
        category: 'Music',
        description: 'Music streaming with offline access.',
        buyRate: 83.50,
        sellRate: 81.40,
        popularityRank: 101,
      ),
      GiftCardModel(
        id: '102',
        name: 'Adidas',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'Germany',
        countryFlag: '🇩🇪',
        category: 'Fashion',
        description: 'Streetwear and sportswear delivery.',
        buyRate: 87.20,
        sellRate: 85.00,
        popularityRank: 102,
      ),
      GiftCardModel(
        id: '103',
        name: 'Puma',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'Germany',
        countryFlag: '🇩🇪',
        category: 'Fashion',
        description: 'Athleisure and lifestyle apparel.',
        buyRate: 85.60,
        sellRate: 83.40,
        popularityRank: 103,
      ),
      GiftCardModel(
        id: '104',
        name: 'Foot Locker',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Fashion',
        description: 'Sneakers and athletic wear.',
        buyRate: 86.30,
        sellRate: 84.10,
        popularityRank: 104,
      ),
      GiftCardModel(
        id: '105',
        name: 'JD Sports',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United Kingdom',
        countryFlag: '🇬🇧',
        category: 'Fashion',
        description: 'Urban street fashion retailer.',
        buyRate: 85.80,
        sellRate: 83.60,
        popularityRank: 105,
      ),
      GiftCardModel(
        id: '106',
        name: 'H&M',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'Sweden',
        countryFlag: '🇸🇪',
        category: 'Fashion',
        description: 'Fast-fashion apparel and lifestyle.',
        buyRate: 84.90,
        sellRate: 82.70,
        popularityRank: 106,
      ),
      GiftCardModel(
        id: '107',
        name: 'Zara',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'Spain',
        countryFlag: '🇪🇸',
        category: 'Fashion',
        description: 'Contemporary fashion shopping.',
        buyRate: 84.20,
        sellRate: 82.00,
        popularityRank: 107,
      ),
      GiftCardModel(
        id: '108',
        name: 'ASOS',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United Kingdom',
        countryFlag: '🇬🇧',
        category: 'Fashion',
        description: 'Global online fashion marketplace.',
        buyRate: 83.60,
        sellRate: 81.40,
        popularityRank: 108,
      ),
      GiftCardModel(
        id: '109',
        name: 'Boohoo',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United Kingdom',
        countryFlag: '🇬🇧',
        category: 'Fashion',
        description: 'Fast-moving apparel trends.',
        buyRate: 82.80,
        sellRate: 80.70,
        popularityRank: 109,
      ),
      GiftCardModel(
        id: '110',
        name: 'Fashion Nova',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Fashion',
        description: 'Trend-focused clothing and beauty.',
        buyRate: 83.20,
        sellRate: 81.10,
        popularityRank: 110,
      ),
      GiftCardModel(
        id: '111',
        name: 'Gucci',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'Italy',
        countryFlag: '🇮🇹',
        category: 'Fashion',
        description: 'Prime luxury fashion purchases.',
        buyRate: 82.40,
        sellRate: 80.30,
        popularityRank: 111,
      ),
      GiftCardModel(
        id: '112',
        name: 'Louis Vuitton',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'France',
        countryFlag: '🇫🇷',
        category: 'Fashion',
        description: 'Luxury leather goods and fashion.',
        buyRate: 81.70,
        sellRate: 79.60,
        popularityRank: 112,
      ),
      GiftCardModel(
        id: '113',
        name: 'Google Play',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Tech',
        description: 'Digital content and app store credit.',
        buyRate: 93.10,
        sellRate: 91.00,
        popularityRank: 113,
      ),
      GiftCardModel(
        id: '114',
        name: 'Microsoft',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Tech',
        description: 'Software and service subscriptions.',
        buyRate: 92.40,
        sellRate: 90.20,
        popularityRank: 114,
      ),
      GiftCardModel(
        id: '115',
        name: 'Samsung',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'South Korea',
        countryFlag: '🇰🇷',
        category: 'Tech',
        description: 'Device ecosystem and digital credits.',
        buyRate: 88.90,
        sellRate: 86.80,
        popularityRank: 115,
      ),
      GiftCardModel(
        id: '116',
        name: 'Dell',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Tech',
        description: 'Computer hardware and accessories.',
        buyRate: 87.50,
        sellRate: 85.40,
        popularityRank: 116,
      ),
      GiftCardModel(
        id: '117',
        name: 'HP',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Tech',
        description: 'Premium hardware and support plans.',
        buyRate: 86.60,
        sellRate: 84.40,
        popularityRank: 117,
      ),
      GiftCardModel(
        id: '118',
        name: 'Lenovo',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'China',
        countryFlag: '🇨🇳',
        category: 'Tech',
        description: 'Business and gaming hardware.',
        buyRate: 85.90,
        sellRate: 83.70,
        popularityRank: 118,
      ),
      GiftCardModel(
        id: '119',
        name: 'ASUS',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'Taiwan',
        countryFlag: '🇹🇼',
        category: 'Tech',
        description: 'High-performance computing solutions.',
        buyRate: 85.30,
        sellRate: 83.10,
        popularityRank: 119,
      ),
      GiftCardModel(
        id: '120',
        name: 'Acer',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'Taiwan',
        countryFlag: '🇹🇼',
        category: 'Tech',
        description: 'Performance laptop and accessory credits.',
        buyRate: 84.70,
        sellRate: 82.50,
        popularityRank: 120,
      ),
      GiftCardModel(
        id: '121',
        name: 'Adobe',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Tech',
        description: 'Creative cloud software and tools.',
        buyRate: 90.40,
        sellRate: 88.20,
        popularityRank: 121,
      ),
      GiftCardModel(
        id: '122',
        name: 'Canva',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'Australia',
        countryFlag: '🇦🇺',
        category: 'Tech',
        description: 'Design subscription and templates.',
        buyRate: 85.10,
        sellRate: 83.00,
        popularityRank: 122,
      ),
      GiftCardModel(
        id: '123',
        name: 'GitHub',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Tech',
        description: 'Developer tools and coding subscriptions.',
        buyRate: 87.70,
        sellRate: 85.60,
        popularityRank: 123,
      ),
      GiftCardModel(
        id: '124',
        name: 'DigitalOcean',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Tech',
        description: 'Cloud hosting and web infrastructure.',
        buyRate: 84.40,
        sellRate: 82.20,
        popularityRank: 124,
      ),
      GiftCardModel(
        id: '125',
        name: 'Namecheap',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Tech',
        description: 'Domain and hosting subscriptions.',
        buyRate: 83.80,
        sellRate: 81.70,
        popularityRank: 125,
      ),
      GiftCardModel(
        id: '126',
        name: 'Sephora',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'France',
        countryFlag: '🇫🇷',
        category: 'Lifestyle',
        description: 'Beauty and luxury self-care shopping.',
        buyRate: 87.10,
        sellRate: 84.90,
        popularityRank: 126,
      ),
      GiftCardModel(
        id: '127',
        name: 'Ulta Beauty',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Lifestyle',
        description: 'Beauty products and salon essentials.',
        buyRate: 86.40,
        sellRate: 84.20,
        popularityRank: 127,
      ),
      GiftCardModel(
        id: '128',
        name: 'Bath & Body Works',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Lifestyle',
        description: 'Home fragrance and self-care goods.',
        buyRate: 85.20,
        sellRate: 83.10,
        popularityRank: 128,
      ),
      GiftCardModel(
        id: '129',
        name: 'Barnes & Noble',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Lifestyle',
        description: 'Books, media, and reading supplies.',
        buyRate: 84.60,
        sellRate: 82.40,
        popularityRank: 129,
      ),
      GiftCardModel(
        id: '130',
        name: 'Audible',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732228.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Lifestyle',
        description: 'Audiobooks and spoken entertainment.',
        buyRate: 88.00,
        sellRate: 85.80,
        popularityRank: 130,
      ),
      GiftCardModel(
        id: '131',
        name: 'Scribd',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732228.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Lifestyle',
        description: 'Books, audiobooks, and digital media.',
        buyRate: 84.10,
        sellRate: 81.90,
        popularityRank: 131,
      ),
      GiftCardModel(
        id: '132',
        name: 'The Body Shop',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United Kingdom',
        countryFlag: '🇬🇧',
        category: 'Lifestyle',
        description: 'Body care and skincare essentials.',
        buyRate: 83.70,
        sellRate: 81.60,
        popularityRank: 132,
      ),
      GiftCardModel(
        id: '133',
        name: 'Udemy',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Education',
        description: 'Online professional learning.',
        buyRate: 88.60,
        sellRate: 86.40,
        popularityRank: 133,
      ),
      GiftCardModel(
        id: '134',
        name: 'Coursera',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Education',
        description: 'Learning and skills programs.',
        buyRate: 87.90,
        sellRate: 85.70,
        popularityRank: 134,
      ),
      GiftCardModel(
        id: '135',
        name: 'edX',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Education',
        description: 'University-level online education.',
        buyRate: 85.70,
        sellRate: 83.50,
        popularityRank: 135,
      ),
      GiftCardModel(
        id: '136',
        name: 'Skillshare',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Education',
        description: 'Creative classes and workshops.',
        buyRate: 84.90,
        sellRate: 82.70,
        popularityRank: 136,
      ),
      GiftCardModel(
        id: '137',
        name: 'Codecademy',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Education',
        description: 'Interactive coding education.',
        buyRate: 86.20,
        sellRate: 84.10,
        popularityRank: 137,
      ),
      GiftCardModel(
        id: '138',
        name: 'Pluralsight',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Education',
        description: 'Tech learning and certification paths.',
        buyRate: 85.40,
        sellRate: 83.20,
        popularityRank: 138,
      ),
      GiftCardModel(
        id: '139',
        name: 'DataCamp',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'Belgium',
        countryFlag: '🇧🇪',
        category: 'Education',
        description: 'Data science and AI learning.',
        buyRate: 84.20,
        sellRate: 82.00,
        popularityRank: 139,
      ),
      GiftCardModel(
        id: '140',
        name: 'LinkedIn Learning',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Education',
        description: 'Professional development and courses.',
        buyRate: 86.80,
        sellRate: 84.60,
        popularityRank: 140,
      ),
      GiftCardModel(
        id: '141',
        name: 'Babbel',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'Germany',
        countryFlag: '🇩🇪',
        category: 'Education',
        description: 'Online language learning.',
        buyRate: 84.00,
        sellRate: 81.90,
        popularityRank: 141,
      ),
      GiftCardModel(
        id: '142',
        name: 'Rosetta Stone',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Education',
        description: 'Immersive language learning solution.',
        buyRate: 83.40,
        sellRate: 81.30,
        popularityRank: 142,
      ),
      GiftCardModel(
        id: '143',
        name: 'MTN',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'Nigeria',
        countryFlag: '🇳🇬',
        category: 'Mobile',
        description: 'Mobile top-up and telecom credit.',
        buyRate: 82.90,
        sellRate: 80.80,
        popularityRank: 143,
      ),
      GiftCardModel(
        id: '144',
        name: 'Airtel',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'India',
        countryFlag: '🇮🇳',
        category: 'Mobile',
        description: 'Telecom recharge and data bundles.',
        buyRate: 82.10,
        sellRate: 79.90,
        popularityRank: 144,
      ),
      GiftCardModel(
        id: '145',
        name: 'Glo',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'Nigeria',
        countryFlag: '🇳🇬',
        category: 'Mobile',
        description: 'Mobile connectivity and recharge credits.',
        buyRate: 81.80,
        sellRate: 79.60,
        popularityRank: 145,
      ),
      GiftCardModel(
        id: '146',
        name: '9mobile',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'Nigeria',
        countryFlag: '🇳🇬',
        category: 'Mobile',
        description: 'Mobile discount and top-up store.',
        buyRate: 80.90,
        sellRate: 78.70,
        popularityRank: 146,
      ),
      GiftCardModel(
        id: '147',
        name: 'AT&T',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Mobile',
        description: 'Wireless service and prepaid mobile credit.',
        buyRate: 88.20,
        sellRate: 86.10,
        popularityRank: 147,
      ),
      GiftCardModel(
        id: '148',
        name: 'Verizon',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Mobile',
        description: 'Wireless and network service credit.',
        buyRate: 87.40,
        sellRate: 85.30,
        popularityRank: 148,
      ),
      GiftCardModel(
        id: '149',
        name: 'T-Mobile',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Mobile',
        description: 'Mobile plan and data top-up credits.',
        buyRate: 86.80,
        sellRate: 84.70,
        popularityRank: 149,
      ),
      GiftCardModel(
        id: '150',
        name: 'Vodafone',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United Kingdom',
        countryFlag: '🇬🇧',
        category: 'Mobile',
        description: 'Telecom plus mobile service recharge.',
        buyRate: 84.90,
        sellRate: 82.80,
        popularityRank: 150,
      ),
      GiftCardModel(
        id: '151',
        name: 'Orange',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'France',
        countryFlag: '🇫🇷',
        category: 'Mobile',
        description: 'Network credit and telecom reloads.',
        buyRate: 83.60,
        sellRate: 81.50,
        popularityRank: 151,
      ),
      GiftCardModel(
        id: '152',
        name: 'O2',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United Kingdom',
        countryFlag: '🇬🇧',
        category: 'Mobile',
        description: 'Mobile data and phone service plans.',
        buyRate: 83.10,
        sellRate: 81.00,
        popularityRank: 152,
      ),
      GiftCardModel(
        id: '153',
        name: 'EE',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United Kingdom',
        countryFlag: '🇬🇧',
        category: 'Mobile',
        description: 'Telecom and connection bundles.',
        buyRate: 82.70,
        sellRate: 80.60,
        popularityRank: 153,
      ),
      GiftCardModel(
        id: '154',
        name: 'Binance Gift Card',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'Singapore',
        countryFlag: '🇸🇬',
        category: 'Crypto',
        description: 'Crypto exchange and digital payment value.',
        buyRate: 88.40,
        sellRate: 86.20,
        popularityRank: 154,
      ),
      GiftCardModel(
        id: '155',
        name: 'Bybit Gift Card',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'Singapore',
        countryFlag: '🇸🇬',
        category: 'Crypto',
        description: 'Digital exchange access and crypto spend.',
        buyRate: 87.10,
        sellRate: 85.00,
        popularityRank: 155,
      ),
      GiftCardModel(
        id: '156',
        name: 'OKX Gift Card',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'Singapore',
        countryFlag: '🇸🇬',
        category: 'Crypto',
        description: 'Crypto wallet and exchange credit.',
        buyRate: 86.40,
        sellRate: 84.30,
        popularityRank: 156,
      ),
      GiftCardModel(
        id: '157',
        name: 'Bitrefill',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Crypto',
        description: 'Crypto-powered gift card ecosystem.',
        buyRate: 85.10,
        sellRate: 82.90,
        popularityRank: 157,
      ),
      GiftCardModel(
        id: '158',
        name: 'Crypto Voucher',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Crypto',
        description: 'Flexible crypto value card.',
        buyRate: 84.40,
        sellRate: 82.20,
        popularityRank: 158,
      ),
      GiftCardModel(
        id: '159',
        name: 'Fanatics',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Sports',
        description: 'Official sports merch and collectibles.',
        buyRate: 86.70,
        sellRate: 84.50,
        popularityRank: 159,
      ),
      GiftCardModel(
        id: '160',
        name: 'NBA Store',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Sports',
        description: 'Basketball sportswear and gear.',
        buyRate: 85.60,
        sellRate: 83.40,
        popularityRank: 160,
      ),
      GiftCardModel(
        id: '161',
        name: 'NFL Shop',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Sports',
        description: 'Football and licensed apparel store.',
        buyRate: 85.20,
        sellRate: 83.00,
        popularityRank: 161,
      ),
      GiftCardModel(
        id: '162',
        name: 'MLB Shop',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Sports',
        description: 'Baseball gear and collectibles.',
        buyRate: 84.60,
        sellRate: 82.50,
        popularityRank: 162,
      ),
      GiftCardModel(
        id: '163',
        name: 'UFC Store',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Sports',
        description: 'Mixed martial arts merchandise.',
        buyRate: 84.10,
        sellRate: 82.00,
        popularityRank: 163,
      ),
      GiftCardModel(
        id: '164',
        name: 'Formula 1 Store',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United Kingdom',
        countryFlag: '🇬🇧',
        category: 'Sports',
        description: 'F1 gear and race-day products.',
        buyRate: 83.80,
        sellRate: 81.70,
        popularityRank: 164,
      ),
      GiftCardModel(
        id: '165',
        name: 'Decathlon',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'France',
        countryFlag: '🇫🇷',
        category: 'Sports',
        description: 'Outdoor, fitness, and sports goods.',
        buyRate: 83.20,
        sellRate: 81.10,
        popularityRank: 165,
      ),
      GiftCardModel(
        id: '166',
        name: 'Nike Sports',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Sports',
        description: 'Performance sportswear and gear.',
        buyRate: 86.30,
        sellRate: 84.20,
        popularityRank: 166,
      ),
      GiftCardModel(
        id: '167',
        name: 'Adidas Sports',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'Germany',
        countryFlag: '🇩🇪',
        category: 'Sports',
        description: 'Athletic performance and activewear.',
        buyRate: 85.40,
        sellRate: 83.30,
        popularityRank: 167,
      ),
      GiftCardModel(
        id: '168',
        name: 'Ulta',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Beauty',
        description: 'Beauty retail and cosmetics access.',
        buyRate: 86.10,
        sellRate: 84.00,
        popularityRank: 168,
      ),
      GiftCardModel(
        id: '169',
        name: 'MAC Cosmetics',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Beauty',
        description: 'Professional makeup and color cosmetics.',
        buyRate: 85.40,
        sellRate: 83.30,
        popularityRank: 169,
      ),
      GiftCardModel(
        id: '170',
        name: 'Fenty Beauty',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Beauty',
        description: 'Inclusive beauty and skin-first products.',
        buyRate: 84.80,
        sellRate: 82.70,
        popularityRank: 170,
      ),
      GiftCardModel(
        id: '171',
        name: 'Lush',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United Kingdom',
        countryFlag: '🇬🇧',
        category: 'Beauty',
        description: 'Cosmetics handmade bath and body goods.',
        buyRate: 83.70,
        sellRate: 81.60,
        popularityRank: 171,
      ),
      GiftCardModel(
        id: '172',
        name: 'Clinique',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Beauty',
        description: 'Skincare and premium beauty solutions.',
        buyRate: 83.10,
        sellRate: 81.00,
        popularityRank: 172,
      ),
      GiftCardModel(
        id: '173',
        name: 'Estee Lauder',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732229.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Beauty',
        description: 'Prestige cosmetics and skincare.',
        buyRate: 82.40,
        sellRate: 80.30,
        popularityRank: 173,
      ),
      GiftCardModel(
        id: '174',
        name: 'CVS Pharmacy',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Health',
        description: 'Pharmacy and wellness essentials.',
        buyRate: 86.40,
        sellRate: 84.20,
        popularityRank: 174,
      ),
      GiftCardModel(
        id: '175',
        name: 'Walgreens',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Health',
        description: 'Pharmacy and everyday wellness purchases.',
        buyRate: 85.80,
        sellRate: 83.60,
        popularityRank: 175,
      ),
      GiftCardModel(
        id: '176',
        name: 'Rite Aid',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Health',
        description: 'Nutrition and health convenience shopping.',
        buyRate: 84.70,
        sellRate: 82.50,
        popularityRank: 176,
      ),
      GiftCardModel(
        id: '177',
        name: 'GNC',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Health',
        description: 'Fitness and supplement marketplace.',
        buyRate: 84.10,
        sellRate: 81.90,
        popularityRank: 177,
      ),
      GiftCardModel(
        id: '178',
        name: 'Vitamin Shoppe',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Health',
        description: 'Nutrition and wellness supplements.',
        buyRate: 83.50,
        sellRate: 81.30,
        popularityRank: 178,
      ),
      GiftCardModel(
        id: '179',
        name: 'MyProtein',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United Kingdom',
        countryFlag: '🇬🇧',
        category: 'Health',
        description: 'Fitness nutrition and training support.',
        buyRate: 82.80,
        sellRate: 80.60,
        popularityRank: 179,
      ),
      GiftCardModel(
        id: '180',
        name: 'Holland & Barrett',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United Kingdom',
        countryFlag: '🇬🇧',
        category: 'Health',
        description: 'Natural wellness and supplement products.',
        buyRate: 81.90,
        sellRate: 79.80,
        popularityRank: 180,
      ),
      GiftCardModel(
        id: '181',
        name: 'Apple Gift Card',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/0/747.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Digital',
        description: 'Digital store credit for Apple services.',
        buyRate: 94.20,
        sellRate: 92.10,
        popularityRank: 181,
      ),
      GiftCardModel(
        id: '182',
        name: 'Dropbox',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Digital',
        description: 'Storage subscription and cloud access.',
        buyRate: 84.50,
        sellRate: 82.40,
        popularityRank: 182,
      ),
      GiftCardModel(
        id: '183',
        name: 'Grammarly',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Digital',
        description: 'AI writing and productivity subscriptions.',
        buyRate: 84.00,
        sellRate: 81.90,
        popularityRank: 183,
      ),
      GiftCardModel(
        id: '184',
        name: 'ChatGPT',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Digital',
        description: 'AI access and premium productivity tools.',
        buyRate: 87.30,
        sellRate: 85.20,
        popularityRank: 184,
      ),
      GiftCardModel(
        id: '185',
        name: 'Amazon AWS',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/732/732177.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Utilities',
        description: 'Cloud computing and infrastructure credits.',
        buyRate: 90.60,
        sellRate: 88.40,
        popularityRank: 185,
      ),
      GiftCardModel(
        id: '186',
        name: 'Google Cloud',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Utilities',
        description: 'Cloud service and server credit.',
        buyRate: 89.70,
        sellRate: 87.50,
        popularityRank: 186,
      ),
      GiftCardModel(
        id: '187',
        name: 'Microsoft Azure',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Utilities',
        description: 'Cloud platform and service subscription.',
        buyRate: 89.30,
        sellRate: 87.10,
        popularityRank: 187,
      ),
      GiftCardModel(
        id: '188',
        name: 'Linode',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Utilities',
        description: 'Cloud hosting and developer services.',
        buyRate: 84.80,
        sellRate: 82.60,
        popularityRank: 188,
      ),
      GiftCardModel(
        id: '189',
        name: 'Vultr',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Utilities',
        description: 'Global cloud compute and hosting.',
        buyRate: 84.10,
        sellRate: 81.90,
        popularityRank: 189,
      ),
      GiftCardModel(
        id: '190',
        name: 'Cloudflare',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Utilities',
        description: 'DDoS mitigation and web performance.',
        buyRate: 83.70,
        sellRate: 81.60,
        popularityRank: 190,
      ),
      GiftCardModel(
        id: '191',
        name: 'GoDaddy',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Utilities',
        description: 'Domains and web hosting plans.',
        buyRate: 83.20,
        sellRate: 81.10,
        popularityRank: 191,
      ),
      GiftCardModel(
        id: '192',
        name: 'Hostinger',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'Lithuania',
        countryFlag: '🇱🇹',
        category: 'Utilities',
        description: 'Hosting solutions and domain services.',
        buyRate: 82.90,
        sellRate: 80.80,
        popularityRank: 192,
      ),
      GiftCardModel(
        id: '193',
        name: 'Bluehost',
        logoUrl: 'https://cdn-icons-png.flaticon.com/512/220/220223.png',
        country: 'United States',
        countryFlag: '🇺🇸',
        category: 'Utilities',
        description: 'Hosting, web building, and domains.',
        buyRate: 82.40,
        sellRate: 80.30,
        popularityRank: 193,
      ),
    ];
  }
}