import '../models/gift_card_region_model.dart';

class RegionService {
  Future<List<GiftCardRegionModel>> loadRegions() async {
    await Future.delayed(const Duration(milliseconds: 220));

    return [
      const GiftCardRegionModel(
        id: 'us',
        countryName: 'United States',
        countryCode: 'US',
        flag: '🇺🇸',
        currencyCode: 'USD',
        currencySymbol: '\u0024',
        buyRate: 93.20,
        sellRate: 95.10,
        availableDenominations: ['100', '250', '500', '1000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'gb',
        countryName: 'United Kingdom',
        countryCode: 'GB',
        flag: '🇬🇧',
        currencyCode: 'GBP',
        currencySymbol: '£',
        buyRate: 91.40,
        sellRate: 93.80,
        availableDenominations: ['50', '100', '200', '500'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'ca',
        countryName: 'Canada',
        countryCode: 'CA',
        flag: '🇨🇦',
        currencyCode: 'CAD',
        currencySymbol: 'C\u0024',
        buyRate: 90.70,
        sellRate: 92.60,
        availableDenominations: ['50', '100', '250', '500'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'au',
        countryName: 'Australia',
        countryCode: 'AU',
        flag: '🇦🇺',
        currencyCode: 'AUD',
        currencySymbol: 'A\u0024',
        buyRate: 89.90,
        sellRate: 91.80,
        availableDenominations: ['50', '100', '250', '500'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'de',
        countryName: 'Germany',
        countryCode: 'DE',
        flag: '🇩🇪',
        currencyCode: 'EUR',
        currencySymbol: '€',
        buyRate: 92.10,
        sellRate: 94.20,
        availableDenominations: ['50', '100', '200', '500'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'fr',
        countryName: 'France',
        countryCode: 'FR',
        flag: '🇫🇷',
        currencyCode: 'EUR',
        currencySymbol: '€',
        buyRate: 91.90,
        sellRate: 93.90,
        availableDenominations: ['50', '100', '200', '500'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'it',
        countryName: 'Italy',
        countryCode: 'IT',
        flag: '🇮🇹',
        currencyCode: 'EUR',
        currencySymbol: '€',
        buyRate: 91.80,
        sellRate: 93.70,
        availableDenominations: ['50', '100', '200', '500'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'es',
        countryName: 'Spain',
        countryCode: 'ES',
        flag: '🇪🇸',
        currencyCode: 'EUR',
        currencySymbol: '€',
        buyRate: 91.70,
        sellRate: 93.60,
        availableDenominations: ['50', '100', '200', '500'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'nl',
        countryName: 'Netherlands',
        countryCode: 'NL',
        flag: '🇳🇱',
        currencyCode: 'EUR',
        currencySymbol: '€',
        buyRate: 92.20,
        sellRate: 94.10,
        availableDenominations: ['50', '100', '250', '500'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'be',
        countryName: 'Belgium',
        countryCode: 'BE',
        flag: '🇧🇪',
        currencyCode: 'EUR',
        currencySymbol: '€',
        buyRate: 91.60,
        sellRate: 93.40,
        availableDenominations: ['50', '100', '200', '500'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'ie',
        countryName: 'Ireland',
        countryCode: 'IE',
        flag: '🇮🇪',
        currencyCode: 'EUR',
        currencySymbol: '€',
        buyRate: 92.00,
        sellRate: 94.00,
        availableDenominations: ['50', '100', '200', '500'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'at',
        countryName: 'Austria',
        countryCode: 'AT',
        flag: '🇦🇹',
        currencyCode: 'EUR',
        currencySymbol: '€',
        buyRate: 91.50,
        sellRate: 93.30,
        availableDenominations: ['50', '100', '200', '500'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'ch',
        countryName: 'Switzerland',
        countryCode: 'CH',
        flag: '🇨🇭',
        currencyCode: 'CHF',
        currencySymbol: 'CHF',
        buyRate: 92.30,
        sellRate: 94.40,
        availableDenominations: ['50', '100', '250', '500'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'pt',
        countryName: 'Portugal',
        countryCode: 'PT',
        flag: '🇵🇹',
        currencyCode: 'EUR',
        currencySymbol: '€',
        buyRate: 91.20,
        sellRate: 93.20,
        availableDenominations: ['50', '100', '200', '500'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'se',
        countryName: 'Sweden',
        countryCode: 'SE',
        flag: '🇸🇪',
        currencyCode: 'SEK',
        currencySymbol: 'kr',
        buyRate: 90.50,
        sellRate: 92.40,
        availableDenominations: ['100', '250', '500', '1000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'no',
        countryName: 'Norway',
        countryCode: 'NO',
        flag: '🇳🇴',
        currencyCode: 'NOK',
        currencySymbol: 'kr',
        buyRate: 90.20,
        sellRate: 92.10,
        availableDenominations: ['100', '250', '500', '1000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'dk',
        countryName: 'Denmark',
        countryCode: 'DK',
        flag: '🇩🇰',
        currencyCode: 'DKK',
        currencySymbol: 'kr',
        buyRate: 90.70,
        sellRate: 92.60,
        availableDenominations: ['100', '250', '500', '1000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'fi',
        countryName: 'Finland',
        countryCode: 'FI',
        flag: '🇫🇮',
        currencyCode: 'EUR',
        currencySymbol: '€',
        buyRate: 91.50,
        sellRate: 93.40,
        availableDenominations: ['50', '100', '200', '500'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'pl',
        countryName: 'Poland',
        countryCode: 'PL',
        flag: '🇵🇱',
        currencyCode: 'PLN',
        currencySymbol: 'zł',
        buyRate: 89.80,
        sellRate: 91.60,
        availableDenominations: ['100', '250', '500', '1000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'ro',
        countryName: 'Romania',
        countryCode: 'RO',
        flag: '🇷🇴',
        currencyCode: 'RON',
        currencySymbol: 'lei',
        buyRate: 89.30,
        sellRate: 91.20,
        availableDenominations: ['100', '250', '500', '1000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'tr',
        countryName: 'Turkey',
        countryCode: 'TR',
        flag: '🇹🇷',
        currencyCode: 'TRY',
        currencySymbol: '₺',
        buyRate: 88.20,
        sellRate: 90.10,
        availableDenominations: ['100', '250', '500', '1000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'ae',
        countryName: 'United Arab Emirates',
        countryCode: 'AE',
        flag: '🇦🇪',
        currencyCode: 'AED',
        currencySymbol: 'د.إ',
        buyRate: 90.10,
        sellRate: 92.00,
        availableDenominations: ['100', '250', '500', '1000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'sa',
        countryName: 'Saudi Arabia',
        countryCode: 'SA',
        flag: '🇸🇦',
        currencyCode: 'SAR',
        currencySymbol: '﷼',
        buyRate: 89.70,
        sellRate: 91.60,
        availableDenominations: ['100', '250', '500', '1000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'qa',
        countryName: 'Qatar',
        countryCode: 'QA',
        flag: '🇶🇦',
        currencyCode: 'QAR',
        currencySymbol: 'ر.ق',
        buyRate: 89.40,
        sellRate: 91.20,
        availableDenominations: ['100', '250', '500', '1000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'kw',
        countryName: 'Kuwait',
        countryCode: 'KW',
        flag: '🇰🇼',
        currencyCode: 'KWD',
        currencySymbol: 'د.ك',
        buyRate: 89.30,
        sellRate: 91.10,
        availableDenominations: ['100', '250', '500', '1000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'za',
        countryName: 'South Africa',
        countryCode: 'ZA',
        flag: '🇿🇦',
        currencyCode: 'ZAR',
        currencySymbol: 'R',
        buyRate: 88.90,
        sellRate: 90.80,
        availableDenominations: ['100', '250', '500', '1000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'ng',
        countryName: 'Nigeria',
        countryCode: 'NG',
        flag: '🇳🇬',
        currencyCode: 'NGN',
        currencySymbol: '₦',
        buyRate: 88.40,
        sellRate: 90.30,
        availableDenominations: ['100', '250', '500', '1000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'gh',
        countryName: 'Ghana',
        countryCode: 'GH',
        flag: '🇬🇭',
        currencyCode: 'GHS',
        currencySymbol: '₵',
        buyRate: 88.10,
        sellRate: 90.00,
        availableDenominations: ['100', '250', '500', '1000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'ke',
        countryName: 'Kenya',
        countryCode: 'KE',
        flag: '🇰🇪',
        currencyCode: 'KES',
        currencySymbol: 'KSh',
        buyRate: 87.90,
        sellRate: 89.70,
        availableDenominations: ['100', '250', '500', '1000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'eg',
        countryName: 'Egypt',
        countryCode: 'EG',
        flag: '🇪🇬',
        currencyCode: 'EGP',
        currencySymbol: 'E£',
        buyRate: 87.70,
        sellRate: 89.50,
        availableDenominations: ['100', '250', '500', '1000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'ma',
        countryName: 'Morocco',
        countryCode: 'MA',
        flag: '🇲🇦',
        currencyCode: 'MAD',
        currencySymbol: 'MAD',
        buyRate: 87.40,
        sellRate: 89.20,
        availableDenominations: ['100', '250', '500', '1000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'jp',
        countryName: 'Japan',
        countryCode: 'JP',
        flag: '🇯🇵',
        currencyCode: 'JPY',
        currencySymbol: '¥',
        buyRate: 90.80,
        sellRate: 92.70,
        availableDenominations: ['1000', '5000', '10000', '20000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'kr',
        countryName: 'South Korea',
        countryCode: 'KR',
        flag: '🇰🇷',
        currencyCode: 'KRW',
        currencySymbol: '₩',
        buyRate: 90.20,
        sellRate: 92.10,
        availableDenominations: ['1000', '5000', '10000', '20000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'cn',
        countryName: 'China',
        countryCode: 'CN',
        flag: '🇨🇳',
        currencyCode: 'CNY',
        currencySymbol: '¥',
        buyRate: 89.90,
        sellRate: 91.80,
        availableDenominations: ['100', '250', '500', '1000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'sg',
        countryName: 'Singapore',
        countryCode: 'SG',
        flag: '🇸🇬',
        currencyCode: 'SGD',
        currencySymbol: 'S\u0024',
        buyRate: 90.40,
        sellRate: 92.20,
        availableDenominations: ['100', '250', '500', '1000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'my',
        countryName: 'Malaysia',
        countryCode: 'MY',
        flag: '🇲🇾',
        currencyCode: 'MYR',
        currencySymbol: 'RM',
        buyRate: 89.80,
        sellRate: 91.70,
        availableDenominations: ['100', '250', '500', '1000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'th',
        countryName: 'Thailand',
        countryCode: 'TH',
        flag: '🇹🇭',
        currencyCode: 'THB',
        currencySymbol: '฿',
        buyRate: 89.20,
        sellRate: 91.00,
        availableDenominations: ['100', '250', '500', '1000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'id',
        countryName: 'Indonesia',
        countryCode: 'ID',
        flag: '🇮🇩',
        currencyCode: 'IDR',
        currencySymbol: 'Rp',
        buyRate: 88.80,
        sellRate: 90.70,
        availableDenominations: ['100000', '250000', '500000', '1000000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'vn',
        countryName: 'Vietnam',
        countryCode: 'VN',
        flag: '🇻🇳',
        currencyCode: 'VND',
        currencySymbol: '₫',
        buyRate: 88.10,
        sellRate: 90.00,
        availableDenominations: ['100000', '250000', '500000', '1000000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'ph',
        countryName: 'Philippines',
        countryCode: 'PH',
        flag: '🇵🇭',
        currencyCode: 'PHP',
        currencySymbol: '₱',
        buyRate: 88.60,
        sellRate: 90.50,
        availableDenominations: ['1000', '2500', '5000', '10000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'in',
        countryName: 'India',
        countryCode: 'IN',
        flag: '🇮🇳',
        currencyCode: 'INR',
        currencySymbol: '₹',
        buyRate: 88.30,
        sellRate: 90.10,
        availableDenominations: ['1000', '2500', '5000', '10000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'pk',
        countryName: 'Pakistan',
        countryCode: 'PK',
        flag: '🇵🇰',
        currencyCode: 'PKR',
        currencySymbol: '₨',
        buyRate: 87.80,
        sellRate: 89.60,
        availableDenominations: ['1000', '2500', '5000', '10000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'br',
        countryName: 'Brazil',
        countryCode: 'BR',
        flag: '🇧🇷',
        currencyCode: 'BRL',
        currencySymbol: 'R\u0024',
        buyRate: 88.70,
        sellRate: 90.50,
        availableDenominations: ['100', '250', '500', '1000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'mx',
        countryName: 'Mexico',
        countryCode: 'MX',
        flag: '🇲🇽',
        currencyCode: 'MXN',
        currencySymbol: '\u0024',
        buyRate: 88.60,
        sellRate: 90.40,
        availableDenominations: ['100', '250', '500', '1000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'ar',
        countryName: 'Argentina',
        countryCode: 'AR',
        flag: '🇦🇷',
        currencyCode: 'ARS',
        currencySymbol: '\u0024',
        buyRate: 88.20,
        sellRate: 90.00,
        availableDenominations: ['100', '250', '500', '1000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'cl',
        countryName: 'Chile',
        countryCode: 'CL',
        flag: '🇨🇱',
        currencyCode: 'CLP',
        currencySymbol: '\u0024',
        buyRate: 88.40,
        sellRate: 90.20,
        availableDenominations: ['10000', '25000', '50000', '100000'],
        isAvailable: true,
      ),
      const GiftCardRegionModel(
        id: 'co',
        countryName: 'Colombia',
        countryCode: 'CO',
        flag: '🇨🇴',
        currencyCode: 'COP',
        currencySymbol: '\u0024',
        buyRate: 88.10,
        sellRate: 90.00,
        availableDenominations: ['100000', '250000', '500000', '1000000'],
        isAvailable: true,
      ),
    ];
  }
}
